# Generated by Django 2.2.6 on 2023-04-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_likee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likee',
            old_name='event',
            new_name='post',
        ),
    ]
